name: influxdb3

networks:
  influxdb3:
  frontend:
    external: true
    
services:
  influxdb2:
    container_name: influxdb3
    image: influxdb:3
    networks: ['influxdb3', 'frontend']
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG:-docs}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET:-home}
    volumes:
      - influxdb3-data:/var/lib/influxdb3
      - influxdb3-config:/etc/influxdb3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.influxdb3-https.tls=true"
      - "traefik.http.routers.influxdb3-https.tls.certresolver=route53"
      - "traefik.http.routers.influxdb3-https.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.influxdb3-https.entrypoints=websecure"
      - "traefik.http.routers.influxdb3-https.service=influxdb3-svc"
      - "traefik.http.services.influxdb3-svc.loadbalancer.server.port=8086"

volumes:
  influxdb3-data:
  influxdb3-config:
